# Generated by Django 3.2 on 2021-05-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20210520_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('المتميز', 'المتميز'), ('الحي الاول', 'الحي الاول'), ('الشيخ زايد', 'الشيخ زايد'), ('الحي التاني', 'الحي التاني'), ('الحي الحادي عشر', 'الحي الحادي عشر'), ('الحي اثني عشر', 'الحي اثني عشر'), ('مدينة نصر', 'مدينة نصر'), ('الحي الرابع', 'الحي الرابع'), ('الحصري', 'الحصري'), ('الحي الثالث', 'الحي الثالث'), ('اكتوبر 6', '6 اكتوبر')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('الساحل الشمالي', 'الساحل الشمالي'), ('الغردقة', 'الغردقة'), ('اسكندرية', 'اسكندرية'), ('الفيوم', 'الفيوم'), ('الاسماعيلية', 'الاسماعيلية'), ('الجيزة', 'الجيزة'), ('العين السخنة', 'العين السخنة'), ('القاهرة الكبري', 'القاهرة الكبري'), ('راس سدر', 'راس سدر')], max_length=100),
        ),
    ]
