# Generated by Django 3.2 on 2021-05-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20210520_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('الحصري', 'الحصري'), ('الحي التاني', 'الحي التاني'), ('الشيخ زايد', 'الشيخ زايد'), ('الحي الثالث', 'الحي الثالث'), ('الحي الرابع', 'الحي الرابع'), ('الحي الحادي عشر', 'الحي الحادي عشر'), ('الحي اثني عشر', 'الحي اثني عشر'), ('اكتوبر 6', '6 اكتوبر'), ('الحي الاول', 'الحي الاول'), ('مدينة نصر', 'مدينة نصر'), ('المتميز', 'المتميز')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('اسكندرية', 'اسكندرية'), ('القاهرة الكبري', 'القاهرة الكبري'), ('الجيزة', 'الجيزة'), ('الساحل الشمالي', 'الساحل الشمالي'), ('الاسماعيلية', 'الاسماعيلية'), ('الفيوم', 'الفيوم'), ('راس سدر', 'راس سدر'), ('العين السخنة', 'العين السخنة'), ('الغردقة', 'الغردقة')], max_length=100),
        ),
    ]
